### ISSUE TITLE
Reference to unknown entry in log during rego demo in video

### ISSUE THREAD

**Issue by Tembrel** [MartianZoo/solarnet#38]
This screen grab from the video refers to entry 422, which doesn't show up in the log:

![image](https://user-images.githubusercontent.com/237258/233139842-5b20a964-b2e9-4f5c-b3d3-df2cc5e80fa6.png)

Are there internal entries that we can't see, or is this a bug?

**Comment by Tembrel** [comment]
Answered later in video.

**Comment by kevinb9n** [comment]
I'm still just delighted to see the first issue filed by not-me :-)
